
[biome_configs]
	#biome list
	deathwormBiomes = ["allthemodium:desert", "allthemodium:desert_hills"]
	#biome list
	lightningDragonBiomes = ["allthemodium:badlands", "allthemodium:badlands_plateau", "allthemodium:eroded_badlands", "allthemodium:modified_badlands_plateau"]
	#biome list
	cockatriceBiomes = ["allthemodium:desert", "allthemodium:desert_hills", "allthemodium:badlands", "allthemodium:badlands_plateau", "allthemodium:eroded_badlands", "allthemodium:modified_badlands_plateau"]
	#biome list
	blackHippogryphBiomes = ["allthemodium:the_other"]
	#biome list
	lightningLilyBiomes = ["allthemodium:desert", "allthemodium:desert_hills"]
	#biome list
	sirenBiomes = ["allthemodium:desert", "allthemodium:desert_hills", "allthemodium:badlands", "allthemodium:badlands_plateau", "allthemodium:eroded_badlands", "allthemodium:modified_badlands_plateau", "allthemodium:basalt_deltas", "allthemodium:gravelly_mountains", "allthemodium:the_other", "allthemodium:mountain_edges"]
	#biome list
	amphithereBiomes = ["allthemodium:badlands_plateau", "allthemodium:crimson_forest", "allthemodium:nether_wastes", "allthemodium:soul_sand_valley", "allthemodium:warped_forest", "allthemodium:the_other"]
	#biome list
	fireDragonSkeletonBiomes = ["allthemodium:badlands_plateau", "allthemodium:crimson_forest", "allthemodium:nether_wastes", "allthemodium:soul_sand_valley", "allthemodium:warped_forest", "allthemodium:the_other"]
	#biome list
	brownHippogryphBiomes = ["allthemodium:basalt_deltas", "allthemodium:gravelly_mountains", "allthemodium:the_other", "allthemodium:mountain_edges"]
	#biome list
	amethystBiomes = ["allthemodium:desert", "allthemodium:desert_hills", "allthemodium:badlands", "allthemodium:badlands_plateau", "allthemodium:eroded_badlands", "allthemodium:modified_badlands_plateau", "allthemodium:basalt_deltas", "allthemodium:gravelly_mountains", "allthemodium:the_other", "allthemodium:mountain_edges"]
	#biome list
	hippocampusBiomes = []
	#biome list
	snowyTrollBiomes = ["allthemodium:gravelly_mountains", "allthemodium:the_other", "allthemodium:mountain_edges"]
	#biome list
	hippogryphBiomes = ["allthemodium:desert", "allthemodium:desert_hills", "allthemodium:badlands", "allthemodium:badlands_plateau", "allthemodium:eroded_badlands", "allthemodium:modified_badlands_plateau", "allthemodium:basalt_deltas", "allthemodium:gravelly_mountains", "allthemodium:the_other", "allthemodium:mountain_edges"]
	#biome list
	iceDragonSkeletonBiomes = ["allthemodium:desert", "allthemodium:desert_hills", "allthemodium:badlands", "allthemodium:badlands_plateau", "allthemodium:eroded_badlands", "allthemodium:modified_badlands_plateau", "allthemodium:basalt_deltas", "allthemodium:gravelly_mountains", "allthemodium:the_other", "allthemodium:mountain_edges"]
	#biome list
	jungleMyrmexBiomes = []
	#biome list
	mausoleumBiomes = ["allthemodium:the_other","allthemodium:mountain_edges","allthemodium:mountains"]
	#biome list
	sapphireBiomes = ["allthemodium:the_other","allthemodium:mountain_edges","allthemodium:mountains" ]
	#biome list
	mountainTrollBiomes = ["allthemodium:mountain_edges","allthemodium:mountains","allthemodium:the_other"]
	#biome list
	iceLilyBiomes = []
	#biome list
	chestnutHippogryphBiomes = ["allthemodium:mountain_edges","allthemodium:nether_wastes"]
	#biome list
	pixieBiomes = []
	#biome list
	creamyHippogryphBiomes = []
	#biome list
	overworldSpawnBiomes = []
	#biome list
	forestTrollBiomes = ["allthemodium:crimson_forest", "allthemodium:warped_forest"]
	#biome list
	grayHippogryphBiomes = ["allthemodium:basalt_deltas", "allthemodium:gravelly_mountains", "allthemodium:the_other", "allthemodium:mountain_edges"]
	#biome list
	seaSerpentBiomes = []
	#biome list
	cyclopsCaveBiomes = ["allthemodium:badlands", "allthemodium:badlands_plateau", "allthemodium:eroded_badlands", "allthemodium:modified_badlands_plateau"]
	#biome list
	stymphalianBiomes = ["allthemodium:basalt_deltas", "allthemodium:gravelly_mountains", "allthemodium:the_other", "allthemodium:mountain_edges"]
	#biome list
	gorgonTempleBiomes = ["allthemodium:badlands", "allthemodium:badlands_plateau", "allthemodium:eroded_badlands", "allthemodium:modified_badlands_plateau","allthemodium:desert"]
	#biome list
	hydraBiomes = ["allthemodium:basalt_deltas", "allthemodium:gravelly_mountains", "allthemodium:the_other", "allthemodium:mountain_edges"]
	#biome list
	whiteHippogryphBiomes = ["allthemodium:desert", "allthemodium:desert_hills"]
	#biome list
	fireLilyBiomes = ["allthemodium:crimson_forest", "allthemodium:nether_wastes", "allthemodium:soul_sand_valley", "allthemodium:warped_forest", "allthemodium:the_other"]
	#biome list
	graveyardBiomes = ["allthemodium:the_other"]
	#biome list
	oreGenBiomes = ["allthemodium:desert", "allthemodium:desert_hills", "allthemodium:badlands", "allthemodium:badlands_plateau", "allthemodium:eroded_badlands", "allthemodium:modified_badlands_plateau", "allthemodium:basalt_deltas", "allthemodium:gravelly_mountains", "allthemodium:the_other", "allthemodium:mountain_edges"]
	#biome list
	iceDragonBiomes = ["allthemodium:gravelly_mountains", "allthemodium:modified_badlands_plateau", "allthemodium:mountain_edges"]
	#biome list
	darkBrownHippogryphBiomes = ["allthemodium:crimson_forest", "allthemodium:nether_wastes", "allthemodium:soul_sand_valley", "allthemodium:warped_forest", "allthemodium:the_other"]
	#biome list
	wanderingCyclopsBiomes = ["allthemodium:nether_wastes", "allthemodium:soul_sand_valley", "allthemodium:warped_forest", "allthemodium:badlands", "allthemodium:badlands_plateau", "allthemodium:eroded_badlands", "allthemodium:modified_badlands_plateau"]
	#biome list
	desertMyrmexBiomes = ["allthemodium:badlands", "allthemodium:badlands_plateau", "allthemodium:eroded_badlands", "allthemodium:modified_badlands_plateau","allthemodium:desert", "allthemodium:desert_hills"]
	#biome list
	lightningDragonSkeletonBiomes = ["allthemodium:badlands", "allthemodium:badlands_plateau", "allthemodium:eroded_badlands", "allthemodium:modified_badlands_plateau"]
	#biome list
	fireDragonBiomes = ["allthemodium:badlands_plateau", "allthemodium:crimson_forest", "allthemodium:nether_wastes", "allthemodium:soul_sand_valley", "allthemodium:warped_forest", "allthemodium:the_other"]

