
[biome_configs]
	#biome list
	deathwormBiomes = ["allthemodium:desert", "allthemodium:desert_hills"]
	#biome list
	lightningDragonBiomes = ["allthemodium:badlands", "allthemodium:badlands_plateau", "allthemodium:eroded_badlands", "allthemodium:modified_badlands_plateau"]
	#biome list
	cockatriceBiomes = ["allthemodium:desert", "allthemodium:desert_hills", "allthemodium:badlands", "allthemodium:badlands_plateau", "allthemodium:eroded_badlands", "allthemodium:modified_badlands_plateau"]
	#biome list
	blackHippogryphBiomes = ["allthemodium:the_other"]
	#biome list
	lightningLilyBiomes = ["allthemodium:desert", "allthemodium:desert_hills"]
	#biome list
	sirenBiomes = []
	#biome list
	amphithereBiomes = ["allthemodium:badlands_plateau", "allthemodium:crimson_forest", "allthemodium:nether_wastes", "allthemodium:soul_sand_valley", "allthemodium:warped_forest", "allthemodium:the_other"]
	#biome list
	fireDragonSkeletonBiomes = ["allthemodium:badlands_plateau", "allthemodium:crimson_forest", "allthemodium:nether_wastes", "allthemodium:soul_sand_valley", "allthemodium:warped_forest", "allthemodium:the_other"]
	#biome list
	brownHippogryphBiomes = ["allthemodium:basalt_deltas", "allthemodium:gravelly_mountains", "allthemodium:the_other", "allthemodium:mountain_edges"]
	#biome list
	amethystBiomes = ["allthemodium:desert", "allthemodium:desert_hills", "allthemodium:badlands", "allthemodium:badlands_plateau", "allthemodium:eroded_badlands", "allthemodium:modified_badlands_plateau", "allthemodium:basalt_deltas", "allthemodium:gravelly_mountains", "allthemodium:the_other", "allthemodium:mountain_edges"]
	#biome list
	hippocampusBiomes = []
	#biome list
	snowyTrollBiomes = []
	#biome list
	hippogryphBiomes = ["allthemodium:desert", "allthemodium:desert_hills", "allthemodium:badlands", "allthemodium:badlands_plateau", "allthemodium:eroded_badlands", "allthemodium:modified_badlands_plateau", "allthemodium:basalt_deltas", "allthemodium:gravelly_mountains", "allthemodium:the_other", "allthemodium:mountain_edges"]
	#biome list
	iceDragonSkeletonBiomes = []
	#biome list
	jungleMyrmexBiomes = []
	#biome list
	mausoleumBiomes = []
	#biome list
	sapphireBiomes = []
	#biome list
	mountainTrollBiomes = []
	#biome list
	iceLilyBiomes = []
	#biome list
	chestnutHippogryphBiomes = []
	#biome list
	pixieBiomes = []
	#biome list
	creamyHippogryphBiomes = []
	#biome list
	overworldSpawnBiomes = []
	#biome list
	forestTrollBiomes = []
	#biome list
	grayHippogryphBiomes = []
	#biome list
	seaSerpentBiomes = []
	#biome list
	cyclopsCaveBiomes = []
	#biome list
	stymphalianBiomes = []
	#biome list
	gorgonTempleBiomes = []
	#biome list
	hydraBiomes = []
	#biome list
	whiteHippogryphBiomes = []
	#biome list
	fireLilyBiomes = []
	#biome list
	graveyardBiomes = ["minecraft:plains", "minecraft:desert", "minecraft:mountains", "minecraft:forest", "minecraft:taiga", "minecraft:swamp", "minecraft:snowy_tundra", "minecraft:snowy_mountains", "minecraft:mushroom_fields", "minecraft:mushroom_field_shore", "minecraft:desert_hills", "minecraft:wooded_hills", "minecraft:taiga_hills", "minecraft:mountain_edge", "minecraft:jungle", "minecraft:jungle_hills", "minecraft:jungle_edge", "minecraft:birch_forest", "minecraft:birch_forest_hills", "minecraft:dark_forest", "minecraft:snowy_taiga", "minecraft:snowy_taiga_hills", "minecraft:giant_tree_taiga", "minecraft:giant_tree_taiga_hills", "minecraft:wooded_mountains", "minecraft:savanna", "minecraft:savanna_plateau", "minecraft:badlands", "minecraft:wooded_badlands_plateau", "minecraft:badlands_plateau", "minecraft:sunflower_plains", "minecraft:desert_lakes", "minecraft:gravelly_mountains", "minecraft:flower_forest", "minecraft:taiga_mountains", "minecraft:swamp_hills", "minecraft:ice_spikes", "minecraft:modified_jungle", "minecraft:modified_jungle_edge", "minecraft:tall_birch_forest", "minecraft:tall_birch_hills", "minecraft:dark_forest_hills", "minecraft:snowy_taiga_mountains", "minecraft:giant_spruce_taiga", "minecraft:giant_spruce_taiga_hills", "minecraft:modified_gravelly_mountains", "minecraft:shattered_savanna", "minecraft:shattered_savanna_plateau", "minecraft:eroded_badlands", "minecraft:modified_wooded_badlands_plateau", "minecraft:modified_badlands_plateau", "minecraft:bamboo_jungle", "minecraft:bamboo_jungle_hills", "biomesoplenty:alps", "biomesoplenty:alps_foothills", "biomesoplenty:bayou", "biomesoplenty:bog", "biomesoplenty:boreal_forest", "biomesoplenty:chaparral", "biomesoplenty:cherry_blossom_grove", "biomesoplenty:cold_desert", "biomesoplenty:coniferous_forest", "biomesoplenty:dead_forest", "biomesoplenty:dryland", "biomesoplenty:fir_clearing", "biomesoplenty:floodplain", "biomesoplenty:flower_meadow", "biomesoplenty:fungal_jungle", "biomesoplenty:grassland", "biomesoplenty:gravel_beach", "biomesoplenty:grove", "biomesoplenty:highland", "biomesoplenty:highland_moor", "biomesoplenty:jade_cliffs", "biomesoplenty:lavender_field", "biomesoplenty:lush_desert", "biomesoplenty:lush_grassland", "biomesoplenty:lush_swamp", "biomesoplenty:mangrove", "biomesoplenty:maple_woods", "biomesoplenty:marsh", "biomesoplenty:meadow", "biomesoplenty:mire", "biomesoplenty:muskeg", "biomesoplenty:mystic_grove", "biomesoplenty:ominous_woods", "biomesoplenty:orchard", "biomesoplenty:origin_valley", "biomesoplenty:outback", "biomesoplenty:overgrown_cliffs", "biomesoplenty:pasture", "biomesoplenty:poppy_field", "biomesoplenty:prairie", "biomesoplenty:pumpkin_patch", "biomesoplenty:rainbow_hills", "biomesoplenty:rainforest", "biomesoplenty:redwood_forest", "biomesoplenty:redwood_forest_edge", "biomesoplenty:scrubland", "biomesoplenty:seasonal_forest", "biomesoplenty:shield", "biomesoplenty:shrubland", "biomesoplenty:silkglade", "biomesoplenty:snowy_coniferous_forest", "biomesoplenty:snowy_fir_clearing", "biomesoplenty:snowy_coniferous_forest", "biomesoplenty:snowy_forest", "biomesoplenty:steppe", "biomesoplenty:temperate_rainforest", "biomesoplenty:temperate_rainforest_hills", "biomesoplenty:tropical_rainforest", "biomesoplenty:tropics", "biomesoplenty:tundra", "biomesoplenty:volcanic_plains", "biomesoplenty:wasteland", "biomesoplenty:wetland", "biomesoplenty:woodland"]
	#biome list
	oreGenBiomes = ["allthemodium:desert", "allthemodium:desert_hills", "allthemodium:badlands", "allthemodium:badlands_plateau", "allthemodium:eroded_badlands", "allthemodium:modified_badlands_plateau", "allthemodium:basalt_deltas", "allthemodium:gravelly_mountains", "allthemodium:the_other", "allthemodium:mountain_edges"]
	#biome list
	iceDragonBiomes = []
	#biome list
	darkBrownHippogryphBiomes = []
	#biome list
	wanderingCyclopsBiomes = []
	#biome list
	desertMyrmexBiomes = []
	#biome list
	lightningDragonSkeletonBiomes = ["allthemodium:badlands", "allthemodium:badlands_plateau", "allthemodium:eroded_badlands", "allthemodium:modified_badlands_plateau"]
	#biome list
	fireDragonBiomes = ["allthemodium:badlands_plateau", "allthemodium:crimson_forest", "allthemodium:nether_wastes", "allthemodium:soul_sand_valley", "allthemodium:warped_forest", "allthemodium:the_other"]

