
[biome_configs]
	#biome list
	deathwormBiomes = ["allthemodium:desert", "allthemodium:desert_hills"]
	#biome list
	lightningDragonBiomes = ["allthemodium:badlands", "allthemodium:badlands_plateau", "allthemodium:eroded_badlands", "allthemodium:modified_badlands_plateau"]
	#biome list
	cockatriceBiomes = ["allthemodium:desert", "allthemodium:desert_hills", "allthemodium:badlands", "allthemodium:badlands_plateau", "allthemodium:eroded_badlands", "allthemodium:modified_badlands_plateau"]
	#biome list
	blackHippogryphBiomes = ["allthemodium:the_other"]
	#biome list
	lightningLilyBiomes = ["allthemodium:desert", "allthemodium:desert_hills"]
	#biome list
	sirenBiomes = []
	#biome list
	amphithereBiomes = ["allthemodium:badlands_plateau", "allthemodium:crimson_forest", "allthemodium:nether_wastes", "allthemodium:soul_sand_valley", "allthemodium:warped_forest", "allthemodium:the_other"]
	#biome list
	fireDragonSkeletonBiomes = ["allthemodium:badlands_plateau", "allthemodium:crimson_forest", "allthemodium:nether_wastes", "allthemodium:soul_sand_valley", "allthemodium:warped_forest", "allthemodium:the_other"]
	#biome list
	brownHippogryphBiomes = ["allthemodium:basalt_deltas", "allthemodium:gravelly_mountains", "allthemodium:the_other", "allthemodium:mountain_edges"]
	#biome list
	amethystBiomes = ["allthemodium:desert", "allthemodium:desert_hills", "allthemodium:badlands", "allthemodium:badlands_plateau", "allthemodium:eroded_badlands", "allthemodium:modified_badlands_plateau", "allthemodium:basalt_deltas", "allthemodium:gravelly_mountains", "allthemodium:the_other", "allthemodium:mountain_edges"]
	#biome list
	hippocampusBiomes = []
	#biome list
	snowyTrollBiomes = []
	#biome list
	hippogryphBiomes = ["allthemodium:desert", "allthemodium:desert_hills", "allthemodium:badlands", "allthemodium:badlands_plateau", "allthemodium:eroded_badlands", "allthemodium:modified_badlands_plateau", "allthemodium:basalt_deltas", "allthemodium:gravelly_mountains", "allthemodium:the_other", "allthemodium:mountain_edges"]
	#biome list
	iceDragonSkeletonBiomes = []
	#biome list
	jungleMyrmexBiomes = []
	#biome list
	mausoleumBiomes = []
	#biome list
	sapphireBiomes = []
	#biome list
	mountainTrollBiomes = []
	#biome list
	iceLilyBiomes = []
	#biome list
	chestnutHippogryphBiomes = []
	#biome list
	pixieBiomes = []
	#biome list
	creamyHippogryphBiomes = []
	#biome list
	overworldSpawnBiomes = []
	#biome list
	forestTrollBiomes = []
	#biome list
	grayHippogryphBiomes = []
	#biome list
	seaSerpentBiomes = []
	#biome list
	cyclopsCaveBiomes = []
	#biome list
	stymphalianBiomes = []
	#biome list
	gorgonTempleBiomes = []
	#biome list
	hydraBiomes = []
	#biome list
	whiteHippogryphBiomes = []
	#biome list
	fireLilyBiomes = []
	#biome list
	graveyardBiomes = ["allthemodium:the_other"]
	#biome list
	oreGenBiomes = ["allthemodium:desert", "allthemodium:desert_hills", "allthemodium:badlands", "allthemodium:badlands_plateau", "allthemodium:eroded_badlands", "allthemodium:modified_badlands_plateau", "allthemodium:basalt_deltas", "allthemodium:gravelly_mountains", "allthemodium:the_other", "allthemodium:mountain_edges"]
	#biome list
	iceDragonBiomes = []
	#biome list
	darkBrownHippogryphBiomes = []
	#biome list
	wanderingCyclopsBiomes = []
	#biome list
	desertMyrmexBiomes = []
	#biome list
	lightningDragonSkeletonBiomes = ["allthemodium:badlands", "allthemodium:badlands_plateau", "allthemodium:eroded_badlands", "allthemodium:modified_badlands_plateau"]
	#biome list
	fireDragonBiomes = ["allthemodium:badlands_plateau", "allthemodium:crimson_forest", "allthemodium:nether_wastes", "allthemodium:soul_sand_valley", "allthemodium:warped_forest", "allthemodium:the_other"]

