
#Biome config
#To filter biomes by registry name "mod_id:biome_id"
#To filter biomes by category "@category"
#To filter biomes by tags "#tag"
#	Examples:
#		"minecraft:plains"
#		"@desert"
#		"#overworld"
#
#If you want to exclude biomes put a ! before the biome identifier
#	Examples:
#		"!minecraft:plains"
#		"!@desert"
#		"!#nether"
#
#If you want to include biomes that would be satisfied by any in a set use |
#	Examples:
#		"|minecraft:plains"
#		"|@desert"
#		"|#nether"
#
#If you want a condition that MUST be satisfied use an & before the biome identifier
#Please note using this on a registry name wouldn't be that useful
#	Examples:
#		"&minecraft:plains"
#		"&@forest"
#		"&#overworld"
#
#NOTE: Any entry without a !, |, or & symbol has a higher precedence
#A list like ["!minecraft:plains", "#overworld"] would still see the plains as a viable biome
#
#Finally, you can create a expression that can be evaluated by itself using a + to combine identifiers
#	Examples:
#		"!#hot+!#dry+!#mountain"
#
#These expressions can be used to filter biomes in a lot of ways
#Lets say we don't want anything to spawn in any place dry and sandy
#	"!#dry+!#sandy"
#
#But there is a hot place we want them to spawn that's also wet
#	"#hot+#wet"
#
#We just put them as separate values in the list and that'll work out
#	["!#dry+!#sandy","#hot+#wet"]
#
#NOTE: Any entry that's an expression will not be affected by anything else in the list
[biome_configs]
	overworldSpawnBiomes = ["|allthemodium:the_other"]
	oreGenBiomes = ["|allthemodium:the_other"]
	sapphireBiomes = ["&allthemodium:the_other+&#snowy+|@icy+|#cold+"]
	amethystBiomes = ["&allthemodium:the_other+|@savanna+|#savanna"]
	fireLilyBiomes = ["&allthemodium:the_other+|#hot+"]
	iceLilyBiomes = ["&allthemodium:the_other+&#snowy+|@icy+|#cold+"]
	lightningLilyBiomes = ["&allthemodium:the_other+|@savanna+|#savanna"]
	fireDragonBiomes = ["&allthemodium:the_other+|#hot+|#plains+!#wet+!#cold+!#forest+!#jungle+!#mesa+!#savanna"]
	iceDragonBiomes = ["&allthemodium:the_other+|@icy+|#snowy+|#cold+"]
	lightningDragonBiomes = ["&allthemodium:the_other+|#jungle+|#mesa+|#savanna+"]
	gorgonTempleBiomes = ["&allthemodium:the_other+|@beach+|#beach"]
	cyclopsCaveBiomes = ["&allthemodium:the_other+|@beach+|#beach"]
	hippogryphBiomes = ["&allthemodium:the_other+|#mesa+|#mountains+|#hills+|@extreme_hills"]
	pixieBiomes = ["&allthemodium:the_other+|#rare+|#magical+|#dense+&#forest+!@taiga+!#hills+!#mountain+!#wet+!#hot+!#cold+!#dry"]
	hippocampusBiomes = ["&allthemodium:the_other+|@ocean+|#ocean"]
	seaSerpentBiomes = ["&allthemodium:the_other+|@ocean+|#ocean"]
	sirenBiomes = ["&allthemodium:the_other+|@ocean+|#ocean"]
	amphithereBiomes = ["&allthemodium:the_other+|#jungle"]
	desertMyrmexBiomes = ["&allthemodium:the_other+|@desert"]
	jungleMyrmexBiomes = ["&allthemodium:the_other+|#jungle"]
	snowyTrollBiomes = ["&allthemodium:the_other+|#snowy+|#cold"]
	forestTrollBiomes = ["&allthemodium:the_other+|@forest+|#forest"]
	mountainTrollBiomes = ["&allthemodium:the_other+|#mountains+|@extreme_hills"]
	stymphalianBiomes = ["&allthemodium:the_other+|@swamp+|#swamp+"]
	hydraBiomes = ["&allthemodium:the_other+|@swamp+|#swamp+"]
	mausoleumBiomes = ["&allthemodium:the_other+&#snowy+|@icy+|#cold+"]
	graveyardBiomes = ["&allthemodium:the_other+!@ocean+!#ocean+!@beach+!#beach"]
	cockatriceBiomes = ["&allthemodium:the_other+|@savanna+|#savanna"]
	deathwormBiomes = ["&allthemodium:the_other+|@desert"]
	wanderingCyclopsBiomes = ["&allthemodium:the_other+|@plains+|#plains"]
	lightningDragonSkeletonBiomes = ["&allthemodium:the_other+|@savanna+|#savanna"]
	fireDragonSkeletonBiomes = ["&allthemodium:the_other+|@desert"]
	iceDragonSkeletonBiomes = ["&allthemodium:the_other+&#snowy+|@icy+|#cold+"]
	blackHippogryphBiomes = ["allthemodium:desert_hills"]
	brownHippogryphBiomes = ["&allthemodium:the_other+|#mountains+|@extreme_hills"]
	grayHippogryphBiomes = ["allthemodium:dark_forest_hills"]
	chestnutHippogryphBiomes = ["allthemodium:wooded_mountains"]
	creamyHippogryphBiomes = ["allthemodium:savanna_plateau"]
	darkBrownHippogryphBiomes = ["allthemodium:taiga_mountains", "allthemodium:taiga_hills"]
	whiteHippogryphBiomes = ["allthemodium:snowy_mountains", "allthemodium:snowy_taiga_mountains", "allthemodium:snowy_taiga_hills"]
